### ISSUE TITLE
Bug: Player online scheduler 

### ISSUE THREAD

**Issue by Bratah123** [Descended/MaplestoryDiscBot#4]
In the ``on_ready`` event of the discord bot. The get_online_players() scheduler is never awaited, which would cause problems if the feature was ever enabled.

Suggestion :
  - Add await get_online_players().start() where appropriate

**Comment by KOOKIIEStudios** [comment]
See [Max_Feeder](https://github.com/KOOKIIEStudios/Max_Feeder/blob/d5b6b7006dfdbf934182f41953f14c35b81535b5/src/main.py#L74)

**Comment by Descended** [comment]
Fixed in commit [52b563f4995ebe9a6c397e51f6a51d5a8abf53e5](https://github.com/Descended/MaplestoryDiscBot/commit/52b563f4995ebe9a6c397e51f6a51d5a8abf53e5)
